with open("input.txt","r") as f:
    x=list(f.readline())
    lista1=(list(x))
    print("Lista initiala este",lista1)
    lista2=sorted(lista1)
    print("Lista crescatoare este",lista2)
    lista3=list(x)
    lista3.sort(reverse=True)
    print("Lista descrescator=",lista3)
    print("Lungimea=",len(lista1))
    print("cel mai mare nr este",max(lista1))
    print("cel mai mic nr este",min(lista1))
    lista4=list(x)
    lista4.extend([111])
    print("Lista + 111 =",lista4)
    lista5=list(x)
    lista5.insert(2,222)
    print("Lista cu 222 pe pozitia 2 ",lista5)